services:
  - type: web
    name: voicebot-demo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false  # Will be set in Render dashboard
      - key: OPENAI_MODEL
        value: gpt-4o-realtime-preview-2024-12-17
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info