name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        python -c "import src.server; print('Server imports OK')"
        python -c "import src.flight_handler; print('Flight handler imports OK')"
    
    - name: Check for secrets
      run: |
        # Fail if any secrets are found
        ! grep -r "sk-" . --exclude-dir=.git --exclude-dir=venv --exclude="*.md"
        ! grep -r "OPENAI_API_KEY=" . --exclude-dir=.git --exclude-dir=venv --exclude="*.md"
        echo "✅ No secrets found in code"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        if [ -n "$RENDER_API_KEY" ] && [ -n "$RENDER_SERVICE_ID" ]; then
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
          echo "✅ Deployment triggered on Render"
        else
          echo "⚠️ Render deployment skipped - add RENDER_API_KEY and RENDER_SERVICE_ID to GitHub Secrets"
        fi